### ISSUE TITLE
Please remove unneeded logs

### ISSUE THREAD

**Issue by tgagor** [sous-chefs/squid#32]
I have such error:

>   22:  # variables
>   23:  ipaddress = node['ipaddress']
>   24:  listen_interface = node['squid']['listen_interface']
>   25:  version = node['squid']['version']
>   26>> netmask = node['network']['interfaces'][listen_interface]['addresses'][ipaddress]['netmask']
>   27:  
>   28:  # squid/libraries/default.rb
>   29:  acls = squid_load_acls
>   30:  host_acl = squid_load_host_acl
>   31:  url_acl = squid_load_url_acl
>   32:  
>   33:  # Log variables to Chef::Log::debug()
>   34:  Chef::Log.debug("Squid listen_interface: #{listen_interface}")
>   35:  Chef::Log.debug("Squid ipaddress: #{ipaddress}")

This is on squid in LVS configuration, have three interfaces: eth0, lo and lo:0

I found that in attributes you have (I suppose this have to remove lo device but this didn't work on my machine):

> default['squid']['listen_interface'] = node['network']['interfaces'].dup.reject { |k, v| k == 'lo' }.keys.first

Then in recipe:

> listen_interface = node['squid']['listen_interface']
> netmask = node['network']['interfaces'][listen_interface]['addresses'][ipaddress]['netmask']
> 
> Chef::Log.debug("Squid listen_interface: #{listen_interface}")
> Chef::Log.debug("Squid netmask: #{netmask}")

And this Log.debug invocations are the only place where this variables are used :-)
Please remove or fix this.

**Comment by juliandunn** [comment]
Sorry I'm not clear what you are asking here. What is your listen interface? Can you post the error you are seeing?

**Comment by gagor** [comment]
Attribute node['squid']['listen_interface'] is used only in debug messages and it was causing error in my configuration (with multiple interfaces).
Sorry for unclear message - it was quite clear for me when I was writing it, but now it's really embroiled :)

**Comment by jperville** [comment]
Hi @juliandunn and @gagor 

I just stumbled on that error also, because the first interface on my system that is not 'lo' happens to be unconfigured (eth0 has no cable but eth1 has, so `node['ipaddress']` resolves to the eth1 interface). The attribute code in this cookbook will implicitly set `default['squid']['listen_interface']` to `eth0` even if eth0 has no address.

At first, I tried modifying the code that computes the default value for `node['squid']['listen_interface']` by changing it to something like this:

```ruby
# attributes/default.rb
default['squid']['ipaddress'] = node['ipaddress']
default['squid']['listen_interface'] = node['network']['interfaces'].dup.detect { |_k, v| v['addresses'].key?(node['squid']['ipaddress']) }.first
```

Then I figured out that the `squid['squid']['listen_interface']` is not used by any recipe or template in this cookbook except for outputting the value and the netmask. Since the attribute is not used (other than for outputting the message), it should IMO be removed OR become used, for example to restrict the interface that squid is listening on.

I think that's what the OP meant when he submitted this PR.

**Comment by juliandunn** [comment]
Yeah, I think I see what you mean now. Want to put in a PR to remove it? (option 1)

**Comment by jperville** [comment]
Actually, I'm about to start deploying squid properly using this cookbook, so I expect to submit a few PRs during the next weeks. Of course, I can submit a PR for option 1 (trivial), but before that I would like to try implementing option 2 (I may need it soon).

**Comment by gagor** [comment]
@juliandunn I just sent PR.

**Comment by jperville** [comment]
After investigating, I vote for option 1 (remove the useless code and attributes), because it is trivial to bind squid to a single interface by setting `node['squid']['port']` to "host:port".

**Comment by Xorima** [comment]
Closing as old issue, please reopen if this is still a problem?
